language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: 
  nosetests --with-coverage --cover-package=IceCat

env:
  global:
    - secure: "vwe5U7hrKR9U8S+McDro9rhG8DlNF/LYJzNA/T77wKNbg/YS5za/vEAh8t0Z59Ad9u6ow0HBU36EJhVEthiiKjciGDj/XiAcRlZBxngB3Er0Mq5nFxNBkR3WzIzxyS5ZnNiEumDXl9yveLw8zPbhycp1XxJP6T1ZkfdV43Gb/gGeI2cSS8somltbL2UgP2JplmD3tS5MqhwnaxWHRbMWjHg+8l5mI8aC+9G7HIfMRwhElROjNQa1Y3uVGLC5UN3fzjAS1OtP39fnf9XRZKuCgw6chDNjNBcVWBD9S96uJAw0venGC3u4RxHi9uqF27WQMV65J8Gj38M3QpAQ4+laXb5YvbZTGVLoK8ju54Y23GAR4EYloilxvfsEdswWTO6GrnFD/d2gpaS+GLCy2t/BeWSZytZ+GUdPsYvO2ArBtJJA+F87fVtcUiptQ27m5h4y8AeWuZ7HTUrZvy6v40MoyaZX3yYa4nFC+HBoSuQ/68u/lEJUPY5WJCxtxjsXX4ciwrkPvBED78ZcRtAYnXrXA8jFk0+qBv4u9GrI/8Bh8nld5cj3J0r0Px4HbUz7/J3p5Jdw/0pvanPCmFikM1PmehUjB0N2QeFuZZ5ozwbdgm83Akqq4f/hKoa26D+PAc16veC+0McDN0LegVx7w8uoK8j2QGQ1PjgIAhTyH60sIXg="
    - secure: "RMIb3r0dxMfU+cMKLJqma9DmodOxY3/BfQ6RyTSms7bzMHocTKYoqW5wqE43olG7SFONVYg4vyudzVhNT1weN+h90C5AK8bppQ1GGaiTTWS/QEKiFrWx78hsOgPl3OrCz/mJXIAAwwtw61HTE41OBEiZvJgGgacTFPlMqPJl9zx0CQAeehr39JtOiWFoaU8WObeVVy+Nii+9+m8OMAsAxF/s8+wc48lvoCXP1VDF4bZGAd842yVPPEvo2mIhgCj+h1UhjW2Yf4GnL9m5UOtlGIYgeudy37mS223WxrxHudq4vnkOQbJqV2V3uTLua1jJCOvUYPIGuLn0WnjEYIQfaUWR1tEHnQzN7b1Su1eXDUrLVmvrH+je1CHUXJr64HOj8+HwV07ZRfPDJb5VPogMi46g9c7FgA1TVKzinjrdBeL2j+tg+EbVari3aRUb+RpnZscoO6PuAOkiSeMMF7neb8jRckgE5QiMTNCb+omNq1b+5OtPVutjhKmwRIguLkdQk+YPQ/0NwZk3oplI/vNsJ5JYk87YaaSBzAgYWHjC2I9mAkUbNt6pRG5ZJrMhh/Fmtwt2gyvJnUdMd8Gcoaiaf1K3QkU9y0UBCTqyTvoAJeE7qQgNRJaI1c9iiPXmc221pxMcJf7B7l+4q8Te8ll3z4Q/VovyqZg3DM7umFEVpk8="    

after_success:
    - coveralls